data = load('mm1data.out');
X = data(:, 2);
Y = data(:, 3);
hold on;
stairs(X, Y);
arrive = data(:, 1)==1;
plot(X(arrive), Y(arrive), 'xr');
depart = data(:, 1)==2;
plot(X(depart), Y(depart), 'xb');
try_eat = data(:, 1)==4;
plot(X(try_eat), Y(try_eat), 'oy');
go_eat = data(:, 1)==5;
plot(X(go_eat), Y(go_eat), 'oc');
come_back = data(:, 1)==6;
plot(X(come_back), Y(come_back), 'og');
balk = data(:, 1)==7;
plot(X(balk), Y(balk), 'xk');
xlabel('TIME'); ylabel('NUMBER OF CUSTOMERS IN QUEUE');
hold off;